server:
  port: 8081  # Tomcat default port

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    controllers: DEBUG

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: insulin-calculator
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092

    patientEvents-topic: patientEvents-topic