logging:
  level:
    root: INFO
    org.springframework.web: INFO
    controllers: DEBUG
    org.springframework.boot.sql.init: DEBUG
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  datasource:
    url: jdbc:sqlite:patients.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  main:
    web-application-type: none

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: patient-checkin
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092

    patientEvents-topic: patientEvents-topic
    patientStatic-topic: patient-static-topic
    patientMetrics-topic: patient-metrics-topic
    mqttEvents-topic: smart-healthcare-data

