server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      schema-registry-url: http://localhost:9010
      group-id: camunda-orchestrator
      auto-offset-reset: earliest

    producer:
      bootstrap-servers: localhost:9092

    patientEvents-topic: patientEvents-topic
    mqttEvents-topic: smart-healthcare-data
    nfcEvents-topic: nfc-events-enriched
    scaleEvents-topic: scale-events

rest:
    insulin-calculator-url: http://localhost:8095/calculateInsulin

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  filter.create: All Tasks
  generic-properties:
    properties:
      historyTimeToLive: P1D
  history-level: FULL